name: Bug Report
description: File an enhancement proposal
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: >
        Thanks for taking the time to fill out this bug report! Before submitting your issue, please make
        sure there isn't already a prior issue concerning this. If there is, please join that discussion instead.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: >
        Describe the bug in detail. Include what you are experiencing.
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: >
        Include any relevant information about your environment. For example:
          - Router version: 1.2.1
          - OS: Ubuntu 24.04
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Reproduction Steps
      description: >
        Provide a step-by-step guide to reproduce the bug.
        For example:
          1. Go to '...'
          2. Click on '....'
          3. Scroll down to '....'
          4. See error
    validations:
        required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: >
        Describe what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
